baseURL = "https://AriesChen-UPC.github.io/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "en"
# 网站语言, 仅在这里 CN 大写
languageCode = "en"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "AriesChen's Blog"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "DoIt"

[params]
  # DoIt 主题版本
  version = "0.3.X"
  # 网站描述
  description = "This is AriesChen's personal website"

[menu]
  [[menu.main]]
    identifier = "post"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "Article"
    url = "/post/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

# [params.home.profile]
  # Gravatar 邮箱, 用于优先在主页显示的头像
  # gravatarEmail = "chenlijiong1105@gmail.com"
  # 主页显示头像的 URL
  # avatarURL = ""
  # 头像的链接指向的 URL
  # avatarLinkURL = ""

# 主页配置
[params.home]
  # DoIt 新增 | 0.2.0 RSS 文章数目
  rss = 10
  # 主页个人信息
  [params.home.profile]
    enable = true
    # Gravatar 邮箱, 用于优先在主页显示的头像
    gravatarEmail = "chenlijiong1105@gmail.com"
    # 主页显示头像的 URL
    # 将你的头像文件放置于 static 或者 assets 目录下
    # 文件路径是相对于 static 或者 assets 目录的
    avatarURL = ""
    # 头像的链接指向的 URL
    avatarLinkURL = ""
    # DoIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
    title = ""
    # 主页显示的网站副标题
    subtitle = "This is AriesChen's personal website"
    # 是否为副标题显示打字机动画
    typeit = true
    # 是否显示社交账号
    social = true
    # DoIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
    disclaimer = ""
  # 主页文章列表
  [params.home.posts]
    enable = true
    # 主页每页显示文章数量
    paginate = 6
    # DoIt 删除 | 0.2.0 被 params.page 中的 hiddenFromHomePage 替代
    # 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
    defaultHiddenFromHomePage = false

[params.social]
    GitHub = "AriesChen-UPC"
    Linkedin = "aries-chen-43106b223"
    Twitter = "AriesChen_UPC"
    Reddit = "AriesChen_UPC"
    Strava = "99309668"
    Medium = "@arieschen_upc"
    Facebook = "profile.php?id=100035507053466"
    Youtubechannel = "UCgykbjgRcV1IFPB1lRAVgJQ"
    Googlescholar = "user=PYwC09AAAAAJ&hl=en"
    Email = "chenlijiong1105@gmail.com"
